main:
  - name: Home
    url: ""
    weight: 1
  - name: About
    url: "#about"
    weight: 2
  - name: About
    url: "#about"
    weight: 3
  - name: Service
    url: "#service"
    weight: 4
  - name: Work
    url: "#portfolio"
    weight: 5
  - name: Resume
    url: "#resume"
    weight: 6
  - name: Skills
    url: "#skills"
    weight: 7
  - name: Blog
    url: "#blog"
    weight: 8
sitemap:
  - name: About me
    url: "#about"
    weight: 1
  - name: See if I am qualified
    url: "#resume"
    weight: 2
  - name: Have a look at my work
    url: "#portfolio"
    weight: 3
  - name: Latest Articles by me
    url: "blog"
    weight: 4
